image: "node:18"

variables:
  POSTGRES_DATABASE: evcar
  POSTGRES_ROOT_PASSWORD: z00m_ZOom
  POSTGRES_DB: evcar
  POSTGRES_HOST: aftermath.team

stages:
  - prepare
  - checks
  - test
  - build
  - package
  - deploy

.before_script_template: &build_test-integration
  before_script:
    - cp .env.example .env
    - yarn install

# prepare stage - install all deps
deps:node:
  stage: prepare
  script:
    - yarn install
  cache:
    key: "backend-node"
    paths:
      - node_modules
    policy: pull-push

# checks stage
eslint:
  stage: checks
  script:
    - yarn install
    - ./node_modules/.bin/eslint ./src --ext .ts  --quiet
  dependencies:
    - deps:node
  cache:
    key: "backend-node"
    paths:
      - node_modules/
    policy: pull

typescript:
  stage: checks
  script:
    - yarn install
    - ./node_modules/.bin/tsc --project tsconfig.json --noEmit
  dependencies:
    - deps:node
  cache:
    key: "backend-node"
    paths:
      - node_modules/
    policy: pull

prettier:
  stage: checks
  script:
    - yarn install
    - ./node_modules/.bin/prettier -c "./src/**/*.ts"
  cache:
    key: "backend-node"
    paths:
      - node_modules/
    policy: pull

deploy-backend:develop:
  stage: deploy
  script:
    - whoami
    - whereis pm2
    - ls -a
    - tsc && node dist/server.js

  only:
    - develop

