image: "node:18"

variables:
  POSTGRES_DATABASE: evcar
  POSTGRES_ROOT_PASSWORD: z00m_ZOom
  POSTGRES_DB: evcar
  POSTGRES_HOST: aftermath.team

stages:
  - prepare
  - checks
  - test
  - build
  - package
  - deploy
  - review

.before_script_template: &build_test-integration
  before_script:
    - cp .env.example .env
    - sed -i -E "s/POSTGRES_HOST=.+/TEST_MYSQL_HOST=aftermath.team/" .env
    - sed -i -E "s/POSTGRES_USER=.+/TEST_MYSQL_USER=anchori/" .env
    - sed -i -E "s/POSTGRES_DATABASE=.+/TEST_MYSQL_DATABASE=evcar/" .env
    - sed -i -E "s/POSTGRES_PASSWORD=.+/TEST_MYSQL_PASSWORD=z00m_ZOom/" .env
    - yarn install

# prepare stage - install all deps
deps:node:
  stage: prepare
  script:
    - yarn install
  cache:
    key: "backend-node"
    paths:
      - node_modules
    policy: pull-push

# checks stage


deploy:
  stage: deploy

  script:
    - docker run -d -p 8888:8888 node:18
  only:
    - develop

