openapi: "3.0.0"
info:
  version: 1.0.0
  title: EVCAR admin API
  license:
    name: MIT
servers:
  - url: localhost:7777/api/slave
tags:
  - name: Brand
  - name: Brand Image
  - name: Car Model
security:
  - bearerAuth: []
paths:
  /brand:
    $ref: "./components/brand/docs/brand.yaml"
  /brand/{brandId}:
    $ref: "./components/brand/docs/brand-id.yaml"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  # parameters:
  #   $ref: "./apidoc/parameters/index.yaml"
  # schemas:
  #   $ref: "./openapi/schemas/index.yaml"
  # responses:
  #   $ref: "./openapi/responses/index.yaml"
